### ISSUE TITLE
[REQUEST] detect bedrock hacked clients 

### ISSUE THREAD

**Issue by MissGamerz** [re-ovo/Matrix-Issues#2517]
**What features/checks do you need?:**
detection of bedrock hacked clients other anticheats not naming any have moved into this space and also just disabling checks is no longer valid of being compatible as its a get out of jail free card for bedrock cheaters.

there are several bedrock hacked clients out there both free and paid

**Comment by re-ovo** [comment]
1. This is a Java anticheat
2. At present, anti-cheat needs to support many Java versions. If bedrock support is added, it will be very difficult to maintain

**Comment by XxMr1234GamerzxX** [comment]
1. im aware this is a java anticheat its just you say you "support gyser" which means you support bedrock, ignoring they exist isnt supporting them. 

2. support latest software..... 

and your competition in the market has already made the move spartan being one

**Comment by DebuffPvP** [comment]
Just don't add geyser support to your server it's that simple bedrock support isn't a good idea if you want to make a stable minecraft java server for both community and generating revenue since you have 2 different people in different platforms then comes issues like these in which the plugin is made for one system that being java and what you want is a cosmetic benefit that being  geyser
